[tool.black]
line-length = 90
preview = true

[tool.isort]
profile = 'black'
multi_line_output = 3

[tool.ruff]
line-length = 90

select = ["E", "F", "D", "N", "C", "ANN"]
extend-ignore = [
    "ANN101",
    "D213",
    "D203",
    "N802"
]
