name: Check coding style

on:
  push:

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Black Check
        uses: psf/black@stable
        with:
          version: "23.1.0"

  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install isort
        run: |
          pip install isort==5.12.0
      - name: run isort
        run: |
          isort --check-only --quiet .
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install ruff==0.0.239
      - name: Run Ruff
        run: ruff .